### ISSUE TITLE
Using lbm_kv in Phoenix app

### ISSUE THREAD

**Issue by bromoapp** [lindenbaum/lbm_kv#1]
#Hi,

I really need a lightweight distributed kv store, which I find **lbm_kv** suitable for my project.
Do you have any elixir phoenix tutorial which I can use as a guide to use your great project?

P.S. My project is in my github repo [here](https://github.com/bromoapp/portal)

Thanks :)

**Comment by schlagert** [comment]
Unfortunately I personally don't have any Elixir experience (yet), but there's [this](https://github.com/mmmries/dkv/) example application in Elixir I know of.

**Comment by bromoapp** [comment]
Ok thanks :)

**Comment by mmmries** [comment]
Hey @bromoapp I use `lbm_kv` in my phoenix project and it's worked out well so far (~9 month in production so far). The way it works in my app is that when my app starts I call:

```elixir
case Node.list do
      [] ->
        # If I'm the first person in the cluster, then we need to just start the tables
        :ok = :lbm_kv.create(__MODULE__)
      _ ->
        Logger.info "waiting to replicate job statuses: #{Timex.now}"
        # wait up to 60 seconds to replicate data
        # pattern match on :ok so if we timeout waiting for the data we will fail to start and we won't take requests
        :ok = :mnesia.wait_for_tables([__MODULE__], 60_000)
        :ok = :lbm_kv.create(__MODULE__)
        Logger.info "finished replicating job statuses: #{Timex.now}"
    end
```

I have to make sure my nodes are joined into a cluster before the application is started so that mnesia can start cleanly and keep the current state of my keys and values. So I start my app with a `sys.config` like this:

```erlang
[{kernel,
  [
    {sync_nodes_optional, ['gob@ip-10-0-0-1.us-west-2.compute.internal', 'gob@ip-10-0-0-2.us-west-2.compute.internal']},
    {sync_nodes_timeout, 10000}
  ]}
].
```

Then in my app I can just call functions on `:lbm_kv` and pass that module name in. I hope that helps somewhat. I also did some benchmarking to get an idea of the speed of `lbm_kev` and posted [my findings in a gist](https://gist.github.com/mmmries/54c2110bb93af61ebfa1aff36acec9ca). Best of luck.

**Comment by bromoapp** [comment]
To @mmmries thanks a lot :)
